GET http://localhost:5005/tickets

###

GET http://localhost:5005/tickets/642c8d0d42cf70d98cdeefb2

###

POST http://localhost:5005/api/tickets
content-type: application/json

{
   "categoryId": 1,
    "userId": 1,
    "engineerId": 1,
    "priority": 1,
    "title": "First ticket test",
    "estTime": 23,
    "endDate": 2323
}

###

DELETE http://localhost:5005/tickets/642c8d0d42cf70d98cdeefb2

###