version: '3.1'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes: 
      - mongo:/database
    ports:
      - '27017:27017'
volumes:
  mongo:
    driver: local